# run: docker-compose up
version: "3"
services:
  webapp:
    container_name: um-elo__webapp
    build:
      context: ./um-elo/um-elo-services/
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
  mongodb:
    container_name: um-elo__mongodb
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./um-elo-storage:/bitnami/mongodb